/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'florin' at '7/29/16 11:30 PM' with Gradle 2.14
 *
 * @author florin, @date 7/29/16 11:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
